# Delete a user

# Delete an existing user
DELETE {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "userName": "Alias"
}

###

DELETE {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "userName": "Borrar2"
}

###

DELETE {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "userName": 0
}

###

DELETE {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "userName": ""
}

###

DELETE {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer {{authorization}}

{
}