# Create a new user

# With all the fields (required & not-required)
POST {{baseUrl}}/api/users
content-type: application/json

{
  "userName": "Alias",
  "name": "Prueba Post",
  "description": "Descripcion del usuario ...",
  "password": "p4ssw0rd"
}

###

# Without not-required
POST {{baseUrl}}/api/users
content-type: application/json

{
  "userName": "Alias",
  "name": "Prueba Post",
  "password": "p4ssw0rd"
}

###

# Without ALL required
POST {{baseUrl}}/api/users
content-type: application/json

{
}

###

# Without required field name
POST {{baseUrl}}/api/users
content-type: application/json

{
  "userName": "Alias",
  "description": "Descripcion del usuario ...",
  "password": "p4ssw0rd"
}

###

# With role admin
POST {{baseUrl}}/api/users
content-type: application/json

{
  "userName": "Alias",
  "name": "Prueba Post",
  "description": "Descripcion del usuario ...",
  "password": "p4ssw0rd",
  "role": "admin"
}

###

# With wrong data type
POST {{baseUrl}}/api/users
content-type: application/json

{
  "userName": "Validacion1",
  "name": null,
  "description": "",
  "password": "p4ssw0rd"
}