# Create a new user

# With all the fields (required & not-required)
POST {{baseUrl}}/api/users
content-type: application/json

{
  "userName": "Alias",
  "name": "Prueba Post",
  "description": "Descripcion del usuario ...",
  "password": "p4ssw0rd",
  "role": "usuario"
}

###

# Without not-required
POST {{baseUrl}}/api/users
content-type: application/json

{
  "userName": "Alias",
  "name": "Prueba Post",
  "password": "p4ssw0rd",
  "role": "usuario"
}

###

# Without ALL required
POST {{baseUrl}}/api/users
content-type: application/json

{
}

###

# Without required field role
POST {{baseUrl}}/api/users
content-type: application/json

{
  "userName": "Alias",
  "name": "Prueba Post",
  "description": "Descripcion del usuario ...",
  "password": "p4ssw0rd"
}