# Update a user

# Update userName
PUT http://localhost:3001/api/users
content-type: application/json

{
  "userName": "Pruebas",
  "password": "123",
  "field": "userName",
  "newData": "Pruebas_uN"
}

###

# Update name
PUT http://localhost:3001/api/users
content-type: application/json

{
  "userName": "Pruebas",
  "password": "123",
  "field": "name",
  "newData": "Pepe Pepez"
}

###

# Update description
PUT http://localhost:3001/api/users
content-type: application/json

{
  "userName": "Pruebas",
  "password": "123",
  "field": "description",
  "newData": "Usuario para pruebas actualizado"
}

###

# Update password
PUT http://localhost:3001/api/users
content-type: application/json

{
  "userName": "Pruebas",
  "password": "123",
  "field": "password",
  "newData": "1234"
}

###

# Update role
PUT http://localhost:3001/api/users
content-type: application/json

{
  "userName": "Pruebas",
  "password": "123",
  "field": "role",
  "newData": "prueba"
}

###

# Update non existing field
PUT http://localhost:3001/api/users
content-type: application/json

{
  "userName": "Pruebas",
  "password": "123",
  "field": "unknown",
  "newData": "prueba"
}

###

# Update non existing user's name
PUT http://localhost:3001/api/users
content-type: application/json

{
  "userName": "Unknown",
  "password": "123",
  "field": "name",
  "newData": "prueba"
}