# Update a user

# Update username, name & description
PUT {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": 12,
  "userName": "Pruebas",
  "name": "Nuevo nombre",
  "description": "Nueva descripción"
}

###

# Update with id as String Int
PUT {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "12",
  "userName": "Pruebas",
  "name": "Nuevo nombre",
  "description": "Nueva descripción"
}

###

# Update something with wrong id data type
PUT {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": 12.2,
  "userName": "Pruebas",
  "name": "Nuevo nombre",
  "description": "Nueva descripción"
}

###

# Update something with wrong data type
PUT {{baseUrl}}/api/users
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": 12,
  "userName": null,
  "name": "",
  "description": true
}
