# Login as a user

# Login as an existing user
POST {{baseUrl}}/api/login
content-type: application/json

{
  "userName": "Alias",
  "password": "p4ssw0rd"
}

###

# Login as a non existing user
POST {{baseUrl}}/api/login
content-type: application/json

{
  "userName": "Unknown",
  "password": "p4ssw0rd"
}

###

# Login with wrong password
POST {{baseUrl}}/api/login
content-type: application/json

{
  "userName": "Alias",
  "password": "password"
}

###

# Login without params
POST {{baseUrl}}/api/login
content-type: application/json

{
}

###

# Login without password
POST {{baseUrl}}/api/login
content-type: application/json

{
  "userName": "Alias"
}

###

# Login without userName
POST {{baseUrl}}/api/login
content-type: application/json

{
  "password": "123"
}

###

# Login with wrong data type userName
POST {{baseUrl}}/api/login
content-type: application/json

{
  "userName": 1,
  "password": "123"
}

###

# Login with wrong data type password
POST {{baseUrl}}/api/login
content-type: application/json

{
  "userName": "Alias",
  "password": 2
}