# Delete a product

# With all the fields (required & not-required) and token
DELETE  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": 42
}

###

# With id as String Int
DELETE  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "61"
}

###

# Non Existing product
DELETE  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": 0
}

###

# Without ALL required
DELETE  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
}

###

# With wrong id type string
DELETE  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "id"
}

###

# With wrong id type float
DELETE  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": 12.34
}

###

# With wrong id type boolean
DELETE  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": false
}