# Delete a product

# With all the fields (required & not-required) and token
DELETE  http://localhost:3001/api/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsInVzZXJOYW1lIjoiQWxpYXMiLCJyb2xlIjoidXN1YXJpbyIsImlhdCI6MTY3OTIyNTU5NCwiZXhwIjoxNjc5MjI5MTk0fQ.lPtjd8xoAFcpLkcvCHlWx7jwVCM2gALN5ho2WsoAYXY

{
  "name": "Producto Prueba NR"
}

###