# Get all products that their names contain the requested one from the Data Base

# With an existing name
GET {{baseUrl}}/api/products?name=prueba

###

# Without an existing name
GET {{baseUrl}}/api/products?name=unknown

###

# Without a number as name
GET {{baseUrl}}/api/products?name=1

###

# Without name and with a parameter that does not exist
GET {{baseUrl}}/api/products?unknown=unknown