# Create a new product

# With all the fields (required & not-required)
POST http://localhost:3001/api/products
content-type: application/json

{
  "name": "Producto Prueba A",
  "description": "Descripcion del producto ...",
  "userId": 12
}

###

# Without not-required
POST http://localhost:3001/api/products
content-type: application/json

{
"name": "Producto Prueba NR",
"userId": 54
}

###

# Without ALL required
POST http://localhost:3001/api/products
content-type: application/json

{
}