# Create a new product

# With all the fields (required & not-required) and token
POST http://localhost:3001/api/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsInVzZXJOYW1lIjoiQWxpYXMiLCJyb2xlIjoidXN1YXJpbyIsImlhdCI6MTY3OTIyNTU5NCwiZXhwIjoxNjc5MjI5MTk0fQ.lPtjd8xoAFcpLkcvCHlWx7jwVCM2gALN5ho2WsoAYXY

{
  "name": "Producto Prueba A",
  "description": "Descripcion del producto ..."
}

###

# With all the fields (required & not-required) but NO TOKEN
POST http://localhost:3001/api/products
content-type: application/json

{
  "name": "Producto Prueba A",
  "description": "Descripcion del producto ..."
}

###

# Without not-required
POST http://localhost:3001/api/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsInVzZXJOYW1lIjoiQWxpYXMiLCJyb2xlIjoidXN1YXJpbyIsImlhdCI6MTY3OTIyNTU5NCwiZXhwIjoxNjc5MjI5MTk0fQ.lPtjd8xoAFcpLkcvCHlWx7jwVCM2gALN5ho2WsoAYXY

{
"name": "Producto Prueba NR"
}

###

# Without ALL required
POST http://localhost:3001/api/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsInVzZXJOYW1lIjoiQWxpYXMiLCJyb2xlIjoidXN1YXJpbyIsImlhdCI6MTY3OTIyNTU5NCwiZXhwIjoxNjc5MjI5MTk0fQ.lPtjd8xoAFcpLkcvCHlWx7jwVCM2gALN5ho2WsoAYXY

{
}