# Update a product

# With all the fields (required & not-required) and token
PUT  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": 50,
  "name": "Edited name",
  "description": "Edited description"
}

###

# With only one field
PUT  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": 50,
  "name": "Edited name"
}

###

# Non Existing product
PUT  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": 0
}

###

# Without ALL required
PUT  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
}

###

# With wrong id type
PUT  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": "12.2"
}

###

# With wrong parameters type
PUT  {{baseUrl}}/api/products
content-type: application/json
Authorization: Bearer {{authorization}}

{
  "id": 50,
  "name": 1,
  "description": 123
}

###